= Tan Joon Kai, Daniel - Project Portfolio

:repoURL: https://github.com/CS2103JAN2018-F09-B1/main

== Project: Your TA

'''

== Overview

Your TA is a desktop contact and task manager application used to manage the many students and deadlines that a university teaching assistant (TA) has. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 15 kLoC.

== Summary of Contributions

* *Major feature*: Added *tasks* that can be scheduled and a *calendar* that scheduled task would appear in.

** What it does: Allows the user to schedule specific tasks into *Your TA*. The scheduled task will then be displayed on the calendar with a colour code based on the tasks *priority* level.

** Justification: This feature is an entirely new function for the user to manage the deadlines of the array of tasks and deadlines that comes with the job of being a teaching assistant. This makes it such that *Your TA* not only helps manage particulars of students, but also the user's (TA) personal tasks.

** Highlights: This feature is brand new that adds a significant amount of functionality to *Your TA*. It required an in-depth planning process of design. The implementation too was challenging as it required the creation of a fully functional calendar, and linking tasks to the calendar such that only tasks with deadlines scheduled on that day would be displayed on that calendar node.

** Credits: Most of the base code of the `Task` class were adapted from the existing `Person` class.

* *Minor feature*: Added matriculation number field to the people added to *Your TA*. And `find` command now finds matching matriculation numbers to the keyword.

** Justification: *Your TA* is made for teaching assistants in universities, the matriculation number field and the `find` command supporting this field provides more user friendliness when searching for a student.

* *Minor feature*: Added a `toggle` function for the theme (colour scheme) of `Your TA`.

** Justification: This gives the user more freedom to customise `Your TA`.

* *Code contributed*: link:{repoURL}/collated/functional/JoonKai1995.md[functional], link:{repoURL}/collated/test/JoonKai1995.md[test].

* *Other contributions*:

** Enhancements to existing features:

*** Wrote additional test cases for the new task features.

** Documentation:

*** Did cosmetic tweaks to the user guide.

*** Added graphical images to provide a visual aid to the user reading the user guide.

** Community:

*** Helped fix repo bugs due to bad merge conflict resolution between v1.4 and 1.5rc.

<<<

== Contributions to the User Guide

*****
_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
*****

== Task, To-do list and Calendar Features

To see how the task scheduling feature works on the `Todo List` and `Calendar`, select the `Todo Lit` tab located right beside the `Person List` tab.

=== Adding a task: `addTask`

Adds a task to the address book. +
Format: `addTask title/TITLE desc/TASK DESCRIPTION by/DEADLINE priority/PRIORITY`

New tasks will be added into the *To-do list* and *Calendar*.

Examples:

Current date: 03-04-2018 +
The application initially starts with no tasks as displayed in Figure 2:

Command entered: +
`addTask title/Grade Exams desc/Grade mid-terms by/04-04-2018 priority/2`: +
This will add a task, 'Grade mid-terms' into the list with his respective details into the application (Figure ).

Command entered: +
`addTask title/Submit Attendance desc/Submit tutorial attendance by/05-04-2018 priority/3`: +
This will add a task, 'Submit tutorial attendance' into the calendar and to-do list with the respective details into the application (Figure ).

=== Editing a task: `editTask`

Edits a task to the address book. +
Format: `editTask INDEX [title/TASK TITLE] [desc/TASK DESCRIPTION] [by/DEADLINE] [priority/PRIORITY]`

The specified tasks will be edited in the *To-do list* and *Calendar*.

****
* The index refers to the index number shown in the last task listing. The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
****

=== Removing a task: `deleteTask`

Deletes a task in the address book. +
Format: `deleteTask INDEX`

The specified tasks will be deleted from the *To-do list* and *Calendar*.


== Command Summary

...

=== Tasks, To-do list and Calendar commands

*Add Task* `addTask desc/TASK DESCRIPTION by/DEADLINE priority/PRIORITY` +
e.g. `addTask title/Grade Exams desc/Grade mid-terms by/04-04-2018 priority/2`
*Delete Task* `deleteTask INDEX` +
e.g. `deleteTask 1`
*Edit Task* `editTask INDEX [title/TASK TITLE] [desc/TASK DESCRIPTION] [by/DEADLINE] [priority/PRIORITY]`
e.g. `editTask 1 title/Eat Dinner`

== Contributions to the Developer guide

*****
_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
*****

== Design

=== Model

...

The `Task` Class:

* Stores the information of a specific task in the AddressBook
* Information includes: Task Description, Deadline, Priority.
* Implements `UniqueTaskList` that enforces uniqueness of its elements and disallows nulls.
* `Task Description`: Object that stores the task description of the `Task` Object.
[NOTE]
Task's name can contain any alphanumeric characters, but should not be null.
* `Deadline`: Object that stores the deadline of the `Task` Object.
[NOTE]
Deadline should not be dates of the past and should only be in the format dd-mm-yyyy.
* `Priority`: Object that stores the priority of the `Task` Object.
[NOTE]
Priority should only be a value from 1 to 3, 1 being the lowest and 3 being the highest.

The `Task` Class:

* Stores the information of a specific Task in Your TA.
* Information includes: Title, Description, Deadline, Priority.
* Implements `UniqueTaskList` that enforces uniqueness of its elements and disallows nulls.
* `Title` & `TaskDescription`: Object that stores the title and description of the `Task` Object.
[NOTE]
Tasks title and description should only contain alphanumeric characters, and should not be null.
* `Deadline`: Object that stores the deadline of the `Task` Object.
[NOTE]
Deadline should be a valid date that exists and in the format dd-mm-yyyy. Tasks cannot be scheduled in the past. And can only be scheduled at most 6 months in advance. (Based on months: tasks cannot be scheduled on 1st August 2018 if the current date is 31st January 2018).
* `Priority`: Object that stores the priority of the `Task` Object.
[NOTE]
Priority value input can only be a value from 1 to 3. 1 being lowest priority and 3 being highest.

== Implementation

...

=== Toggling Between Themes: Light and Dark (Since v1.5)

This feature allows the user to toggle between 2 preset themes, light and dark.

==== Current implementation

The user will click on the drop-down menu tab labeled `Switch Theme`, and select the `toggle` button to toggle to the other theme that is not currently in use.

==== Design Considerations

===== Aspect: How much freedom is given to the user in terms of customisation

* **Alternative 1 (current choice):** Use 2 preset css files, `LightTheme.css` and `DarkTheme.css`, restrict toggling between these 2 presets only. Change the controller class `MainWindow.java` between 2 fxml files, `DarkMainWindow.fxml` and `LightMainWindow.fxml`.
** Pros: Simple to implement and user friendly. User can switch to a different theme with a click of a button.
** Cons: User cannot customize the themes at all, only have 2 choices, light or dark.
* **Alternative 2:** Allow user to customise and pick a colour for each aspect. e.g. background colour, text colour etc.
** Pros: User have full ability to customise the colours of different aspects the app.
** Cons: Heavy on programming (need to add a lot more cases into the css file(s)). User can create hideous themes.

==== Future enhancements (Coming in v2.0)

Add more themes that can be chosen from the theme drop-down box so that the user has more choices.

=== Tasks on Calendar View (Since v1.5)

This feature allows the user to see the calendar on the UI and see the scheduled `Task` deadlines on the calendar.

==== Current implementation

The user will enter a command `addTask title/TITLE desc/DESCRIPTION by/DEADLINE priority/PRIORITY` to the application. The application will then rely on `AddressBookparser` and
parse the argument. The argument will be passed into the AddTaskCommand to be executed. From there, it will create a new `Task` object that will be
added to the `calendarList` of the `UniqueTaskList` which in turn will be displayed on the date of the deadline, on the calendar.

==== Design Considerations

===== Aspect: How to link specific tasks to the correct calendar nodes

* **Alternative 1 (current choice):** Use a 7 by 32, 2D `Array` to store the tasks to be added into the calendar.
** Pros: Separate from the Task list (less prone to bugs). Faster run time (does not need to iterate through all tasks).
** Cons: Higher memory usage constraint, can only schedule tasks up to 6 months in advance to prevent high memory usage that will affect the speed and performance of the app.
* **Alternative 2:** Use the task list itself to be displayed in the calendar.
** Pros: Easier to program and less memory usage (only 1 task list is used without another 2D array for the calendar), tasks can be scheduled as far ahead as desired.
** Cons: Needs to iterate through the entire task list for every calendar node when loading the calendar view (slows performance when dealing with tasks).

==== Future enhancements (Coming in v2.0)

Link specific key-press or select actions to the todo list such that a click on either side will display the selected task on the other.
