= SHI JIN - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets
:linkattrs:
:repoURL: https://github.com/CS2103JAN2018-F14-B4/main

This portfolio highlights my contributions to the project when studying in School of Computing, National University of Singapore.

== PROJECT: link:{repoURL}[Bibliotek]
---
Bibliotek is a free book cataloguing application that is simple, fast and easy to use.
You can use Bibliotek to search for books, manage your reading list and track the availability of your books.

== Overview

Bibliotek is a desktop book management application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions


* **Encrypt data with a password** (major)
** Add two class cipherEngine and LockManagement to help encrypt/decrypt the data/password and keep the data safe.
** Add an ecrypt data function to let bookshelf.xml to be encrypted when user set a non-default password.
** Add one check of isProtect value in LockManagement to decide whether encrypt the bookshelf.xml before saving the data.
** Add `lock`, `unlock` and `setpw` command to do lock management. If password is not default(""), everytime user open the application,
   he should unlock the bookshelf using password before he can do further instructions.
** This allows users to keep their data private and safe.
* **Mark a book as read, change the priority of a book and rate books** (minor)
** Added attributes rating, (status and priority by others).
** Added `edit` command that allows user to `rating`, set `status` and change `priority` of
some books.
** Added parser for three attributes.
** This allows the user to keep track of what to read and what have been read and give recommendations to others.
* **Set command to be case insensitive**(minor)
** Added case insensitive to the command.
** This allows the user to type in command without worry about the case, and make user easy to use our application.

* *Code contributed*: [https://github.com/CS2103JAN2018-F14-B4/main/tree/master/collated/functional.592363789.md[Functional code]] [https://github.com/CS2103JAN2018-F14-B4/main/tree/master/collated/test.592363789.md[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
** Enhancements to existing features:
*** Added the `ratingbook` command.
*** Added in `Edit` book command. (Pull requests https://github.com/CS2103JAN2018-F14-B4/main/pull/111[#111])
*** Added in `lock` command.
*** Added in `unlock` and `setpw` command.
*** Added in data file encryption and decryption features.
*** Added in the data file encryption enhancement. (Pull requests https://github.com/CS2103JAN2018-F14-B4/main/pull/134[#134])
*** Added one case insensitive feature. (Pull requests https://github.com/CS2103JAN2018-F14-B4/main/pull/179[#179])
** Documentation:
*** Added my major and minor feature into UserGuide and DeveloperGuide, adding my Project Portfolio. (https://github.com/CS2103JAN2018-F14-B4/main/pull/193[#193])
** Community:
*** PRs reviewed. (https://github.com[#12], https://github.com/CS2103JAN2018-F14-B4/main/pull/84[#84], https://github.com/CS2103JAN2018-F14-B4/main/pull/79[#79],
https://github.com/CS2103JAN2018-F14-B4/main/pull/68[#68], https://github.com/CS2103JAN2018-F14-B4/main/pull/44[#44])
*** Reported bugs and suggestions for other teams in the class. (Issues https://github.com/CS2103JAN2018-F11-B3/main/issues/116[#116],
https://github.com/CS2103JAN2018-F11-B3/main/issues/119[#119], https://github.com/CS2103JAN2018-F11-B3/main/issues/133[#133],
https://github.com/CS2103JAN2018-F11-B3/main/issues/137[#137], https://github.com/CS2103JAN2018-F11-B3/main/issues/118[#118],
https://github.com/CS2103JAN2018-F11-B3/main/issues/123[#123])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=edit]

include::../UserGuide.adoc[tag=encrypt]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=edit]

include::../DeveloperGuide.adoc[tag=encrypt]



---
