= Chia Kah Sheng Ellery - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Your TA

---

== Overview

Your TA is an application designed to fulfill the needs of a university tutor. It helps them to manage their students and tasks that they have to do.
Your TA uses a graphical user interface built using JavaFX and the user interacts with the application mostly through a command line interface.
Your TA is written in Java and has about 10 kLoC.

Your TA is build upon https://github.com/se-edu/addressbook-level4[AddressBook - Level 4].

== Summary of contributions

* *Major enhancement*: Added a display picture/status to all persons in the application.
** What it does: It allows the user to save a display picture to any student in the application.

** Justification: This feature provides the tutor with a visual stimulus on how the student looks. This way, the tutor would be able to quickly associate the student's name and their face
which in turn allow the tutor to remember their students better. This would encourage a more holistic environment for teaching and learning as it would make it more
personal between the tutor and the student. Additionally, it also contains a drop shadow frame which shows whether the student has at least participated sufficiently in classes.

** Highlights: This enhancement fully supports the implemented undo and redo even though image files are stored outside the `AddressBook` memory.
The existing commands were also updated to support the adding and changing of display pictures.

** Credits: https://stackoverflow.com/users/2970947/elliott-frisch[Elliott Frisch] from stackoverflow on the SHA-256 hash algorithm used to generate the name of the image file.

* *Minor enhancement*: Added a `Participation` attribute to `Person` to keep track of a student's participation level. It supports the addition of marks to the `Person` object.

* *Code contributed*: [https://github.com/CS2103JAN2018-F09-B1/main/blob/master/collated/functional/Wu.md[Functional code]][https://github.com/CS2103JAN2018-F09-B1/main/blob/master/collated/test/Wu.md[Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.2` (2 releases) on GitHub
*** Manage and set up the organization repo, assigned issues and mange Pull Requests.
*** Set up Coverall for the organization repo.
** Documentation:
*** Updated the screenshots used in the User Guide: https://github.com/CS2103JAN2018-F09-B1/main/pull/57[#57]
** Community:
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/CS2103JAN2018-F12-B2/main/issues/83[1], https://github.com/CS2103JAN2018-F12-B2/main/issues/80[2], https://github.com/CS2103JAN2018-F12-B2/main/issues/76[3])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=participation]

include::../UserGuide.adoc[tag=display]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=participation]

include::../DeveloperGuide.adoc[tag=display]

