= Chan Tiong Ley - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Catalogue

---

== Overview

* This is a desktop Catalogue application. It has a GUI but most of the user interactions happen using a CLI (Command Line Interface).
* It is a Java application intended for librarians, students and guests using the library.
* We started the project based on an AddressBook sample application(https://github.com/nus-cs2103-AY1718S2/addressbook-level4) that is around 10KLoC.

== Summary of contributions

* *Major enhancement*: Added the ability to add and delete account Commands and the add/delete command parsers
** What it does: allows the user to add a new account into the existing account list and delete an account based on the username inside the account list.
** Justification: This feature improves the product significantly because a librarian can create borrowers (with privilege level of student) and create new administrators (with privilege level of librarian). The database of students will allow the students of National University of Singapore to borrow, return and reserve a book of their desire inside the library.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: NIL

* *Minor enhancement*: Improved the CLIsyntax to parse Account Level commands and created the ReserveCommandTests
** What it does: The improved CLISyntax parses the account name, account matriculation number, account Username, account Password and account privilege level to create an account in the system database. For the ReserveCommand tests, the ReserveCommandParserTest was created to check for invalid reserve command word tests and ReserveCommandTest checks if the command created can effectively reserve a "borrowed" book and return an invalid command if we try to reserve an available book.
** Justification: This feature allows the system to parse the parameters necessary to create the user account in the system. The reserve command tests ensures that the reserveCommand can properly serve its function to reserve a "borrowed" book.
** Highlights: This enhancement affects existing commands (addAccount Command and deleteAccount Command) and future commands such as an “edit Account Command”. The implementation required creation of new methods inside the model manager and account sub-classes.

* *Code contributed*:

* *Other contributions*:

** Project management:

** Enhancements to existing features:

** Documentation: Updated documentation on my enhancements.

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=addaccount]

include::../UserGuide.adoc[tag=deleteaccount]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===


include::../DeveloperGuide.adoc[tag=addaccount]

include::../DeveloperGuide.adoc[tag=deleteaccount]

---

