= Chuang Cheng Heng - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Media Socializer

---

== Overview

Media Socializer is a one-stop social media desktop application made to help users to keep track of the many social media platforms they are currently using. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to search for person on social media platforms*
** What it does: allows the user to perform the search function for person's profile on the social media platforms through the application with a single command.
** Justification: This feature grants the user the ability to search for other person's profile on either the stated social media platforms or all the platforms available through the application. Thus, the user no longer need to go on to the different social media platform and perform the search repeatedly. This feature brings the application one step closer to the goal of being an one-stop social media application.
** Highlights: This feature has to be able to display the search results of different social media platforms in a convenient way, as such, it requires the implementor to come up with a UI allows the user to jump between search results easily. The implementation is
** Credits: The design of the UI is inspired by the tab interface of the internet browsers (i.e. Firefox, Google Chrome, and etc)

* *Minor enhancement*: added a findtag command that allows the user to find persons whose tags contain the input keywords.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Ensure the closure of milestone `v1.3` - `v1.5rc` (3 milestones) on GitHub
** Enhancements to existing features:
*** Modified the WebBrowser UI to suit the requirement of Media Socializer (Pull request https://github.com/CS2103JAN2018-F12-B3/main/pull/90[#90])
*** Edited the typical persons to support testing of findtag feature (Commit https://github.com/CS2103JAN2018-F12-B3/main/pull/57/commits/81e4756a3c4b96af8ef241bb2f09b13da5cdc370[1], https://github.com/CS2103JAN2018-F12-B3/main/pull/57/commits/a96b25048d02a8c135a9e59cd3001efa591f64fc[2], https://github.com/CS2103JAN2018-F12-B3/main/pull/57/commits/8c9c32c0f41d9f15e1f8c440491c3eafd35383a0[3])
** Documentation:
*** Update About Us: https://github.com/CS2103JAN2018-F12-B3/main/pull/56[#56]
** Community:
*** Follow up with reported bugs (example: https://github.com/CS2103JAN2018-F12-B3/main/issues/112[1], https://github.com/CS2103JAN2018-F12-B3/main/issues/109[2])



== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=non-functional-requirements]

include::../DeveloperGuide.adoc[tag=dataencryption]
