= Kang Anmin - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ProgressChecker

---

== Overview

ProgressChecker is *a desktop application that enables CS2103/T students to track their learning progress and project development on a centralized platform* throughout the module. The current release is meant to be used alongside with CS2103/T module website. ProgressChecker has a JavaFX GUI, but users will interact with it via CLI for efficiency.

== Summary of contributions

* *Major enhancement*: added *a task list which contains tasks assigned by the lecturers of this module*
** *What it does:* allows students to view tasks by week, mark each task as completed/pending, view web page of each task through URL and check progress (in fraction and percentage).
** *Justification:* this feature solves a significant issue that students faced: they are confused when viewing the collapsible nested list on module website and possibly miss some tasks residing in an inner layer. Also, there are a significant number of tasks each week, which is hard to finish in one go. Thus, they may forget what they have covered when they resume after leaving it for a while. They also cannot tell how far are they away from completing all tasks.
** *Highlights:* This enhancement touches on all 4 components in the code base, which requires a good understanding of the existing architecture of the project prototype. Furthermore, it is implemented with Google Task API and cloud services which requires a lot of exploration. Using external libraries also tests the skills of integrating external resources with current code base.
** *Credits:* Some of the implementation was inspired by the existing code base that has implemented a numerous commands to manage a list of contacts in an address book. The utilization of Google Task API borrows my experience with Google Calendar API when doing an Android application in another project organized by NUS School of Computing called Orbital.

* *Minor enhancement*: added multiple fields of person and update all relevant commands. These fields are used in my teammates' enhancement. added a  progress bar to give a graphic and more intuitive view of the level of completeness of tasks in the task list.

* *Code contributed*: [https://github.com/CS2103JAN2018-T09-B3/main/blob/master/collated/functional/EdwardKSG.md[Functional code]] [https://github.com/CS2103JAN2018-T09-B3/main/blob/master/collated/test/EdwardKSG.md[Test code]]

* *Other contributions*: did refactor of both code and documentations to fit our new project and hide legacy of the prototype project to make it an independent project.

** Project management:
*** Managed issues and pull requests with a wide variety of labels and different milestones.
*** Checked completeness of milestone, closed milestone and made release.
** Enhancements to existing features:
*** Added a new browser panel to allow showing two different pages side by side https://github.com/CS2103JAN2018-T09-B3/main/pull/181[#181]
*** Changed error message of *delete* command to give a clearer suggestion of what the users are doing wrong https://github.com/CS2103JAN2018-T09-B3/main/pull/213[#213]
** Documentation:
*** Wrote the first version of introduction in User and Developer Guide
*** Contributed to User Stories and Use Cases https://github.com/CS2103JAN2018-T09-B3/main/pull/111[#111]
** Community:
*** Pull requests reviewed (with non-trivial review comments): https://github.com/CS2103JAN2018-T09-B3/main/pull/212[#212] https://github.com/CS2103JAN2018-T09-B3/main/pull/209[#209] https://github.com/CS2103JAN2018-T09-B3/main/pull/26[#26] https://github.com/CS2103JAN2018-T09-B3/main/pull/8[#8]
*** Reported bugs and suggestions for other teams in the class https://github.com/CS2103JAN2018-F14-B4/main/issues/149[#149] https://github.com/CS2103JAN2018-F14-B4/main/issues/146[#146]
** Tools:
*** Integrated a https://developers.google.com/google-apps/tasks/[Google Tasks Java API](com.google.api.services.tasks) to the project https://github.com/CS2103JAN2018-T09-B3/main[ProgressChecker].

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=tasks]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=adddefaulttasklist]
