= Eldon Chung - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CoinBook

---

== Overview

CoinBook is a desktop accounting application written in Java. It is targeted at cryptocurrency traders and enthusiasts, and allows them to keep track of the coins they hold, obtain price data and analytics, and read the latest news relevant to them in the same place. Primary interaction is through a CLI, and a GUI built with JavaFX.

== Summary of contributions

* *Major enhancement*: Added *advanced search criteria and boolean logical operators*
** What it does: Allows the user to search through the __CoinBook__ based on Code, price, etc as well as boolean combinations of these.
** Justification: This lets users search through a large set of coins quickly as well as allow users the power of very specific queries.
This allows for ease of use and handling of a large Coin base.
** Highlights: This enhancement involved revamping the entire input sanitation to allow for a higher level of parsing.
The resulting system was then used by enhancements written by other team members. Many alternative design considerations were made and tradeoffs were sacrificed.
** Credits: Concepts of tokenization, parsing, syntax specification and boolean predicate generation were covered extensively in __Compilers: Principles, Techniques, and Tools__ by Alfred V. Aho, Monica S. Lam, Ravi Sethi, and Jeffrey D. Ullman.
The conceptualization of the parser would not have been possible without the valuable lessons obtained from that book.

* *Proposed extensions* :
** Boolean logical queries may be difficult for users to consistently express. One possible enhancement could be to include syntax
highlighting on the text as it is typed in to notify the user when the string is valid without requiring the user to use the `Enter` key.
** It could be very useful to automatically translate such boolean queries into English as the user types the queries, to give them a sense of
what their expression means. For example: when the user keys in `(p/>50 AND t/fav) OR c/BTC` it could be possible for some text
to appear with the following sentence: "Based on this query, you wish to find all coins that are priced above 50 dollars and you have tagged as favourite. Also,
you wish to find the coin named BTC".

** The Tokenizer, along with its TokenTypes and the SyntaxParser was designed to be extensible in the case there needs to be
a drastic change in syntax. An approach to the Unix-style command line interface is another possible direction.

* *Minor enhancement*: Added a news panel which loads subreddits for coins through the view command when invoked. Also provided the ability for __CoinBook__ to warn
the user when the coin added does not exist.

* *Code contributed*: [https://github.com/CS2103JAN2018-F09-B3/main/blob/master/collated/functional/Eldon-Chung.md[Functional code]] [https://github.com/CS2103JAN2018-F09-B3/main/blob/master/collated/test/Eldon-Chung.md[Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.5rc` (1 release) on GitHub
** Enhancements to existing features:
*** Refactored old tests to suit new code base (Pull requests https://github.com/CS2103JAN2018-F09-B3/main/pull/202[#202], https://github.com/CS2103JAN2018-F09-B3/main/pull/202[#211])
*** Refactored entire code base for general quality (https://github.com/CS2103JAN2018-F09-B3/main/pull/147[#147], https://github.com/CS2103JAN2018-F09-B3/main/pull/138[#138],
https://github.com/CS2103JAN2018-F09-B3/main/pull/112[#112], https://github.com/CS2103JAN2018-F09-B3/main/pull/189[#189], https://github.com/CS2103JAN2018-F09-B3/main/pull/204[#204])
*** Reported and addressed bugs (Pull requests https://github.com/CS2103JAN2018-F09-B3/main/pull/183[#183], https://github.com/CS2103JAN2018-F09-B3/main/issues/184[#184], https://github.com/CS2103JAN2018-F09-B3/main/issues/188[#188],
https://github.com/CS2103JAN2018-F09-B3/main/issues/191[#191], https://github.com/CS2103JAN2018-F09-B3/main/issues/192[#192], https://github.com/CS2103JAN2018-F09-B3/main/pull/193[#193])
** Documentation:
*** Managed the UG and DG: (Pull requests https://github.com/CS2103JAN2018-F09-B3/main/pull/121[#121], https://github.com/CS2103JAN2018-F09-B3/main/pull/180[#180], https://github.com/CS2103JAN2018-F09-B3/main/pull/76[#76])
*** Standardised the diagram color scheme and renamed "address to coin" in the UG and DG: (Pull requests https://github.com/CS2103JAN2018-F09-B3/main/commit/01dbe64f74fe4a7a8ce156988d8c25afb0ae64da[1])
** Community:
*** Reported bugs for other teams in the class(examples:  https://github.com/CS2103JAN2018-F12-B3/main/issues/108#event-1570704377[1])

** Tools:
*** Used PlantUML for generating diagrams for the Developer Guide
== Contributions to the User Guide

|===
|_Given below is the main section I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=findcommand]

== Contributions to the Developer Guide

|===
|_Given below is the main section I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=condition]


== PROJECT: PowerPointLabs

---
