= Ewald Hew - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets
:repoLinkBase: https://github.com/CS2103JAN2018-F09-B3/main

== PROJECT: CoinBook

---

== Overview

CoinBook is a desktop accounting application written in Java. It is targeted at cryptocurrency traders and enthusiasts, and allows them to keep track of the coins they hold, obtain price data and analytics, and read the latest news relevant to them in the same place. Primary interaction is through a CLI, and a GUI built with JavaFX.

== Summary of contributions

* *Major enhancement*: Added *user-set notification rules*
** What it does: Allows the user to set rules regarding any property of a coin, e.g. price, profitability, etc., which trigger notifications if the conditions are met upon a price data update.
** Justification: This feature informs the user immediately and draws their attention to the updates that is most relevant to them. Users can set notifications as suits their needs and focus on what's important.
** Highlights: This enhancement requires various backend systems that were implemented by other team members and close coordination of the interfaces and behaviour was challenging but crucial. +
An Event-Driven Design drives the feature and the existing Command pattern was adapted and combined with another design pattern to define custom behaviours upon rule triggers (although it is only used for creating pop-up notifications now).

* *Proposed extensions*: The notifications features was designed with extensibility in mind. It could be upgraded in the future to handle other types of trigger-action pairs, encapsulated by the `Rule` objects. Examples: custom macros, post updates to backup server, generate suggestions from analytics.

* *Minor enhancement*: Added a *charts panel* to the GUI for visualisation of historical price data, which can be extended in the future to display other analytics e.g. candlestick graphs.

* *Code contributed*: [{repoLinkBase}/tree/master/collated/functional/ewaldhew.md[Functional code]] [{repoLinkBase}/tree/master/collated/test/ewaldhew.md[Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.2` - `v1.4` (3 releases) on GitHub
*** Managed issue tracker and milestone planning
*** Recorded issues raised in team meetings into tracker
** Changes to existing features:
*** Refactored many minor parts of the codebase to suit our new product, a good part of which was redefining existing interfaces: (Pull requests)
{repoLinkBase}/pull/87[#87], {repoLinkBase}/pull/98[#98], {repoLinkBase}/pull/106[#106], {repoLinkBase}/pull/108[#108], {repoLinkBase}/pull/118[#118]
*** Made various minor visual changes to the GUI: {repoLinkBase}/pull/263[#263]
** Bug squashing:
*** Helped as part of team effort to fix bugs discovered:
{repoLinkBase}/pull/199[#199], {repoLinkBase}/pull/240[#240],
{repoLinkBase}/pull/244[#244], {repoLinkBase}/pull/268[#268]
** Documentation:
*** Edited layout and language of the Developer and User Guides: {repoLinkBase}/pull/115[#115]
*** Updated diagrams in the Developer Guide: {repoLinkBase}/pull/187[#187]
** Community:
*** PRs reviewed (with non-trivial review comments): {repoLinkBase}/pull/34[#34], {repoLinkBase}/pull/209[#209]
*** Reported bugs and suggestions for other teams in the class (examples:
https://github.com/CS2103JAN2018-T11-B3/main/issues/118[1],
https://github.com/CS2103JAN2018-T11-B3/main/issues/120[2],
https://github.com/CS2103JAN2018-T11-B3/main/issues/126[3],
https://github.com/CS2103JAN2018-T11-B3/main/issues/129[4])
** Tools:
*** Used PlantUML for generating diagrams for the Developer Guide
*** Used AsciiDoctor PDF to render better-looking documentation over printing HTML pages from Chrome

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=notifications]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=notifications]
