= hoangduong1607 - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ReciRecipé

---

== Overview

ReciRecipé is a desktop recipe storage application for users who prefer using the keyboard instead of a mouse for efficient management. It is useful for tech-savvy cooks that want all their recipes stored in one place.

== Summary of contributions

* *Major enhancement*: added *commands auto-completion*
** What it does: helps users quickly type long commands, with all the fields automatically filled. Users can also quickly move from field to field in a command with only their keyboard.
** Justification: This feature improves the product significantly because ReciRecipé is a Command Line Interface application, this feature significantly reduces time to enter commands for users.
** Highlights: This enhancement does not affect commands and internal data of ReciRecipé, it interacts mostly with application's User Interface. It required an in-depth analysis of design alternatives. The implementation was challenging as it required additional components of User Interface and newly added componenets must be suitable with existing compoenets.

* *Minor enhancement*: added `group` and `view_group` commands that allows the user to create and view their own groups, which helps them manage their recipes efficiently.

* *Code contributed*: [https://github.com/CS2103JAN2018-F09-B2/main/blob/master/collated/functional/hoangduong1607.md[Functional code]] [https://github.com/CS2103JAN2018-F09-B2/main/blob/master/collated/test/hoangduong1607.md[Test code]]

* *Other contributions*:

** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2103JAN2018-F09-B2/main/pull/5[#5], https://github.com/CS2103JAN2018-F09-B2/main/pull/12[#12], https://github.com/CS2103JAN2018-F09-B2/main/pull/35[#35], https://github.com/CS2103JAN2018-F09-B2/main/pull/37[#37],
https://github.com/CS2103JAN2018-F09-B2/main/pull/48[#48],
https://github.com/CS2103JAN2018-F09-B2/main/pull/73[#73],
https://github.com/CS2103JAN2018-F09-B2/main/pull/74[#74],
https://github.com/CS2103JAN2018-F09-B2/main/pull/94[#94],

*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/CS2103JAN2018-F12-B4/main/issues/133[1], https://github.com/CS2103JAN2018-F12-B4/main/issues/134[2], https://github.com/CS2103JAN2018-F12-B4/main/issues/138[3])


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

=== *`group`* : Creating a custom group of recipes

Creates a group of one or multiple recipes by the index or indices used in the last recipe listing.

Format: `group group_name/GROUP_NAME index/INDEX [index/INDEX]`

****
* The index refers to the index number shown in the most recent listing.
* The index *must be a positive integer*, e.g. "1, 2, 3, …"..
* Only the name is searched.
* Only full words will be matched e.g. *`find Chic`* will not match `_Chicken_`.
* Recipes matching at least one keyword will be returned (i.e. "OR" search). E.g. *`find Chicken Pizza`* will return `_Chicken rice_` and `_Pizza_`.
****

Examples:

* *`list`* +
*`group group_name/ My best index/ 1 index/ 3`* +
Creates a group that contains 1st recipe and 3rd recipe and names the group as `_My best_`.

https://github.com/CS2103JAN2018-F09-B2/main/blob/master/docs/UserGuide.adoc#strong-code-view_group-code-strong-viewing-groups-of-recipes

=== *`view_group`* : Viewing groups of recipes

Views recipes inside a group.

Format: `view_group GROUP_NAME`

Examples:

* *`view_group My best`* +
Lists all recipes inside `_My best_` group.

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

=== Auto-completion
==== Current implementation

Formerly, users need to type all application keywords and their inputs to the command line. Auto-completion feature is implemented to help users shorten the commands they need to type, by giving suggestions of words based on current input of users and automatically filling chosen words into input field.

Currently, a class called `_SuggestionsPopUp_`, which inherits from `_ContextMenu_`, is created to handle all operations relating to auto-completion. The operations include displaying a pop-up menu consisting of suggestions for user’s input, automatically completing input field when a word is chosen and hiding the pop-up menu.

Key combination kbd:[Shift]+kbd:[Tab] is used to show suggestion pop-up. For other keys and key combinations, the pop-up is hidden. The code to handle these key and key combination actions is shown below:

[source,java]
----
private void handleKeyPress(KeyEvent keyEvent) {
    suggestionsPopUp.hideSuggestions();
    if (SHOW_SUGGESTIONS_COMMAND.match(keyEvent)) {
        keyEvent.consume();
        suggestionsPopUp.showSuggestions();
    }
    // Other key combinations
}
----

To display suggestions, first, a suggestion list is built, then the position of the pop-up menu is calculated for display.

Suggestion list is built with a given list as a dictionary and last word in user input as a word that needs to be looked up. All words in the dictionary that take given word as prefix are valid suggestions and added to the list. However, since `_CommandBox_` is limited, only a small number of words are added to the pop-up menu. The code for compiling suggestion list is given below:

[source,java]
----
for (String suggestion : dictionary) {
    if (suggestion.startsWith(prefix)) {
        addSuggestion(suggestion);
    }

    if (getItems().size() == MAX_SUGGESTIONS) {
        break;
    }
}
----

The given dictionary and the constant `MAX_SUGGESTIONS` can be found in `_AutoCompletionUtil_` class. All operations with input text such as finding the last word of user's input are supported by `_TextInputProcessorUtil_` class.

To calculate position to display pop-up menu, height and width of input text (in pixels) are computed and then used to determine display position in the main window. Height and width of input text are calculated in `_TextInputProcessorUtil_` class.

Then, the suggestion list can be shown in main window.

To hide the suggestion list, a method called `hide()` is implemented as below:

[source,java]
----
protected void hideSuggestions() {
    if  (isShowing()) {
        hide();
    }
}
----

To automatically fill input field with chosen word, an `EventListener` is attached to each item in the pop-up menu. When an item is chosen, it replaces the last word in input field with the word associated with the item. The code is shown below:

[source,java]
----
item.setOnAction(event -> commandBox.replaceText(textInputProcessor.replaceLastWord(item.getText())));
----

`_TextInputProcessorUtil_` object `textInputProcessor` is used to handle an operation `replaceLastWord()` for the given text.

==== Design considerations

===== Aspect: Base class of SuggestionsPopUp.

* **Alternative 1 (current choice):** `_ContextMenu_`.
** Pros: Easy to use since `_ContextMenu_` and `_TextArea_` are in the same library `javafx.scene.control`.
** Cons: Dependent on `_TextArea_` in `_CommandBox_` class.
* **Alternative 2:** `_JPopupMenu_`
** Pros: NA.
** Cons: Need additional work to make `_JPopupMenu_` compatible with `_TextArea_`.

===== Aspect: Abstraction of `_SuggestionsPopUp_`.

* **Alternative 1 (current choice):** A separate class `_SuggestionsPopUp_`.
** Pros: More intuitive approach since `_SuggestionsPopUp_` is a component in `UI`.
** Cons: Need to take extra information from `_CommandBox_` class.
* **Alternative 2:** An inner class of `_CommandBox_` class.
** Pros: Easy to implement since it has access to all attributes and methods of `_CommandBox_`.
** Cons: Limitations in reusability.

===== Aspect: Abstraction of `_TextInputProcessorUtil_`.

* **Alternative 1 (current choice):** A separate class `_TextInputProcessorUtil_`.
** Pros: Common functions easily used by other classes if needed.
** Cons: NA.
* **Alternative 2:** An inner class of `_SuggestionsPopUp_` class.
** Pros: Convenient to use inside the containing class.
** Cons: Limitations in reusability.
