= John Doe - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ET - Employees Tracker

---

== Overview

The Employees Tracker (ET) is a human resource management software. It aims to provide a one-stop solution for managers to manage their subordinates.
Two of its major selling points are employees profile management as well as task tracking.
Since most managers can type fast, ET is designed to have a Command Line Interface (CLI) as to allow its users to carry out operations efficiently without having to switch between the keyboard and mouse.
Nonetheless, ET has a Graphical User Interface (GUI) to allow more direct visual feedbacks.

ET is developed using JAVA 8, and JavaFX and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: *Notification System*
** What it does: It shows notification cards to users to remind them about the expiry of the tasks that they have assigned to their subordinates.
** Justification: Life as a manager is busy. It is very difficult for them to keep track of all the tasks being carried out in his team. This feature alleviates their pain by removing the need for them to remember the details of each task.
** Highlights: This features requires a seamless integration with all other components of the app, from UI to Logic and even storage, in order to work properly.
That said, when designing the interface between the Notification System and each other components, one has to know what is the best design choice, considering the constraints of the component.
Nonetheless, in order to present notifications in an elegant way that doesn't confuses the users, a considerable amount of insights into UX and UI designs is required.

* *Minor enhancement*: added rating feature to allow users to record the performance of each employee.

* *Code contributed*: [https://github.com/CS2103JAN2018-W15-B1/main/blob/master/collated/functional/IzHoBX.md[Functional code] [https://github.com/CS2103JAN2018-W15-B1/main/blob/master/collated/test/IzHoBX.md[Test code]]

* *Other contributions*:

** Project management:
*** Oversees milestone v1.5rc and v1.5 on GitHub
** Enhancements to existing features:
*** Develops the command-suggestion system that gives hints on command usages dynamically according to text that users type (Pull request https://github.com/CS2103JAN2018-W15-B1/main/pull/132/[#132])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** Issues reviewed (with non-trivial review comments): https://github.com/CS2103JAN2018-W15-B1/main/issues/26[#26]
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/CS2103JAN2018-W13-B2/main/issues/128[1], https://github.com/CS2103JAN2018-W13-B2/main/issues/137[2], https://github.com/CS2103JAN2018-W13-B2/main/issues/134[3], https://github.com/CS2103JAN2018-W13-B2/main/issues/130[4])
** Tools:
*** Integrated a third party library (emoji=java) to the project (https://github.com/CS2103JAN2018-W15-B1/main/pull/53/commits/b8fd616f4b40d442d5dee77c1ad77bf86ca1f96e[#53])

== Contributions to the User Guide


|===
|_Given below are my contributions to the User Guide. They showcase my ability to write documentation that are easy to be understood by end-users._
|===

include::../UserGuide.adoc[tag="quickStart"]
include::../UserGuide.adoc[tag="rate"]
include::../UserGuide.adoc[tag="ns"]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to convey technical ideas in a professional and comprehensible way as well as the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=rate]
include::../DeveloperGuide.adoc[tag=ns]
