= Jarrett Choo - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CLIndar

== Overview

CLIndar is a desktop application that helps university computing students manage their tasks and events. The user interacts with it via a Command-Line Interface. Most of the application is written in Java, and its
GUI is written using JavaFX.

== Summary of contributions

* *Major enhancement*: Added *overdue feature*
** What it does: Tags task as "overdue" once it has passed its due date and tags event as "finished" once it has passed its end date automatically.
** Justification: This feature helps users of CLIndar to keep track of their overdue tasks. It also alerts them on the events that have passed.
** Highlights: The "overdue" and "finished" tags are added automatically by the system, thus knowledge on the Java Concurrency API is needed. There is also a need to remove the "overdue" tag when the user completes the task, and this requires integration
with the rest of the system.
** Credits: One problem faced is that the UI cannot be updated by a thread other than the JavaFX application thread. To solve this issue, I refer to Stack Overflow https://stackoverflow.com/questions/21083945/how-to-avoid-not-on-fx-application-thread-currentthread-javafx-application-th[here].

* *Minor enhancement #1*: Added *the ability to add and remove tasks or events*
** What it does: Adds and removes task or event into CLIndar. Event which end date is before its start date is not allowed.
** Highlights: This feature is a modification to the add and delete commands. It takes into account the new model of CLIndar.

* *Minor enhancement #2*: Used *Java 8 Date Time API*
** What it does: Parses the datetimes of tasks and events provided by the user and stores them as LocalDateTime objects. Formats the datetimes for display in the UI.
** Justification: The datetimes are stored as LocalDateTime objects, so that they can be used more easily by other features in CLIndar, such as overdue, which requires comparing between datetimes.

* *Code contributed*: [https://github.com/CS2103JAN2018-W13-B3/main/blob/master/collated/functional/Kyomian.md[Functional code]] [https://github.com/CS2103JAN2018-W13-B3/main/blob/master/collated/test/Kyomian.md[Test code]]

* *Other contributions*:

** Project management:
*** Set up the team repo and added Travis GI, AppVeyor and Coveralls to manage incoming Pull Requests.
*** Set up a new Project in team repo to manage and classify user stories according to their importance.
*** Managed releases `v1.3` - `v1.4` (2 releases) on GitHub.

** Documentation:
*** Wrote the AboutUs: https://github.com/CS2103JAN2018-W13-B3/main/pull/62/files[Pull Request #62]
*** Wrote the basic outline of User Guide: https://github.com/CS2103JAN2018-W13-B3/main/pull/52[Pull Request #52]

** Community:
*** Reported bugs and suggestions for other teams in the class: https://github.com/CS2103JAN2018-T15-B2/main/issues/89[Pull Request #89], https://github.com/CS2103JAN2018-T15-B2/main/issues/96[Pull Request #96], https://github.com/CS2103JAN2018-T15-B2/main/issues/99[Pull Request #99]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=introduction]
include::../UserGuide.adoc[tag=getstarted]
include::../UserGuide.adoc[tag=taskevent]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=overdue]

