= Jasmund - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CLIndar

---

== Overview

CLIndar is a desktop application that helps university computing students to manage their tasks and events. The user interacts with it using a CLI. It has a GUI created with JavaFX, and is written in Java.

== Summary of contributions

* *Major enhancement*: Makeover of the GUI and the ability to display different views of the GUI
** What it does: As the cells do not display full details of the activity, selecting it will allow the full details
of it being displayed in a separate panel which hides if no cell is selected. The user also can choose to
display task or events only, or both.
** Justification: This feature improves the application significantly because it reduces the clutter in the GUI,
making it more appealing and allows the user to switch between different views of the GUI depending on his needs.
** Highlights: This enhancement required in-depth analysis of JavaFx. The implementation too was challenging as
building upon the application to include these enhancement required deep understanding of how the existing
application worked.
** Credits: CalendarFX - third-party library. Zoomable pane - //https://stackoverflow.com/questions/16680295/javafx-correct-scaling

* *Minor enhancement*: Enhanced the existing help command. Allows the user to request for help for the command he specified.

* *Code contributed*: [https://github.com/CS2103JAN2018-W13-B3/main/blob/master/collated/functional/jasmoon.md[Functional code]]
 [https://github.com/CS2103JAN2018-W13-B3/main/blob/master/collated/test/jasmoon.md[Test code]]

* *Other contributions*:

** Project management:
*** Open, tag, assign and close issues.
*** Coming out with most of the user stories for the team's major enhancements.
** Enhancements to existing features:
*** Added 'esc' function feature whereby pressing 'esc' key allows deselection of list cell.
** Documentation:
*** Reviewed the language and grammar of the developer guide.
*** Included and updated pictures and diagrams in the developer guide.
** Community:
*** Reviewed teammate's code before merging pull request.
*** Resolved merge conflicts as a result of a few consecutive pull request.
** Tools:
*** Integrated a third party library (CalendarFX) to the project
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=helpcommand]

include::../UserGuide.adoc[tag=listcommand]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=guiimplementation]

include::../DeveloperGuide.adoc[tag=listcommandaspect]
