= Jonathan Lee - Project Portfolio
:experimental:
:imagesDir: ../images
:stylesDir: ../stylesheets

//@@author jonleeyz
== PROJECT: LoanShark Manager

---

== Overview

HuatAh! is a desktop loan shark manager application. It has a GUI but most of the user interactions happen using a CLI (Command Line Interface).

== Summary of contributions

* *Major enhancement*: added keyboard shortcuts to complement all commands that can be entered into the CommandBox.
** What it does: This feature to press certain keyboard shortcuts to either execute a command immediately or populate
the CommandBox with the necessary prefixes and specifiers required for the input of the Command.
** Justification: This feature improves the product significantly because a typical user of this application will
input many commands throughout the course of his usage and it is easy to make a syntax error or typo if all commands
are manually typed. Some commands such as the AddCommand might require many prefixes and having the prefixes already in
the CommandBox also helps remind the User which values he / she needs or wants to input.
** Highlights: Added menu items, keyboard shortcuts, difference between population and immediate execution, tests, home view
** Pull Requests (functional):
https://github.com/CS2103JAN2018-F12-B4/main/pulls/79[#79], https://github.com/CS2103JAN2018-F12-B4/main/pulls/100[#100],
https://github.com/CS2103JAN2018-F12-B4/main/pulls/107[#107], https://github.com/CS2103JAN2018-F12-B4/main/pulls/125[#125],
https://github.com/CS2103JAN2018-F12-B4/main/pulls/146[#146]
** Pull Requests (tests): https://github.com/CS2103JAN2018-F12-B4/main/pulls09[#109]

* *Minor enhancement*: general UI updates - menu elements, ResultDisplay, CommandBox
** Pull Requests: below

* *Code contributed*:
[https://github.com/CS2103JAN2018-F12-B4/main/tree/master/collated/functional/jonleeyz.md[Functional code]]
[https://github.com/CS2103JAN2018-F12-B4/main/tree/master/collated/functional/jonleeyz-reused.md[Functional code: reused from other sources]]
[https://github.com/CS2103JAN2018-F12-B4/main/tree/master/collated/test/jonleeyz.md[Test code]]
[https://github.com/CS2103JAN2018-F12-B4/main/tree/master/collated/test/jonleeyz.md[Test code: reused from other sources]]

* *Other contributions*:

** Project management:
*** Managed release `v1.4` (1 release) on GitHub
*** Managed the rebrand of the application from LoanShark Manager to HuatAh!: https://github.com/CS2103JAN2018-F12-B4/main/pulls/152[#152]
*** Created user story issues:
https://github.com/CS2103JAN2018-F12-B4/main/issues/23[#23], https://github.com/CS2103JAN2018-F12-B4/main/issues/24[#24],
https://github.com/CS2103JAN2018-F12-B4/main/issues/25[#25], https://github.com/CS2103JAN2018-F12-B4/main/issues/26[#26],
https://github.com/CS2103JAN2018-F12-B4/main/issues/27[#27], https://github.com/CS2103JAN2018-F12-B4/main/issues/28[#28],
https://github.com/CS2103JAN2018-F12-B4/main/issues/29[#29], https://github.com/CS2103JAN2018-F12-B4/main/issues/30[#30],
https://github.com/CS2103JAN2018-F12-B4/main/issues/31[#31], https://github.com/CS2103JAN2018-F12-B4/main/issues/32[#32],
https://github.com/CS2103JAN2018-F12-B4/main/issues/33[#33], https://github.com/CS2103JAN2018-F12-B4/main/issues/34[#34],
https://github.com/CS2103JAN2018-F12-B4/main/issues/35[#35], https://github.com/CS2103JAN2018-F12-B4/main/issues/36[#36],
https://github.com/CS2103JAN2018-F12-B4/main/issues/37[#37], https://github.com/CS2103JAN2018-F12-B4/main/issues/38[#38]

** Enhancements to existing features:
*** Tweaked CommandBox to ignore empty input: https://github.com/CS2103JAN2018-F12-B4/main/pulls/3[#3]
*** Edited prefixes for AddCommand and EditCommand to use ":" instead of "/": https://github.com/CS2103JAN2018-F12-B4/main/pulls/45[#45]
*** Added colours to tags: https://github.com/CS2103JAN2018-F12-B4/main/pulls/64[#64]
*** Tweaked ResultDisplay to style its output red if invalid commands are entered: https://github.com/CS2103JAN2018-F12-B4/main/pulls/67[#67]
*** Tweaked ResultDisplay to make it big enough to display 5 lines: https://github.com/CS2103JAN2018-F12-B4/main/pulls/143[#143]
*** Tweaked structure of all command messages for readability: https://github.com/CS2103JAN2018-F12-B4/main/pulls/143[#143]
*** Fix inconsistencies in command messages: https://github.com/CS2103JAN2018-F12-B4/main/pulls/149[#149]
*** Added 15 sample `Runners` and `Customers` to the sample data: https://github.com/CS2103JAN2018-F12-B4/main/pulls/151[#151]

** Documentation:
*** Overhauled structure and cosmetic style of the User Guide:
https://github.com/CS2103JAN2018-F12-B4/main/pulls/81[#81],
https://github.com/CS2103JAN2018-F12-B4/main/pulls/81[#112],
https://github.com/CS2103JAN2018-F12-B4/main/pulls/122[#122],
https://github.com/CS2103JAN2018-F12-B4/main/pulls/143[#143]
*** Fix inconsistencies in the User and Developer Guides: https://github.com/CS2103JAN2018-F12-B4/main/pulls/149[#149]
*** Removed unused photos from `docs` folder: https://github.com/CS2103JAN2018-F12-B4/main/pulls/66[#66]

** Community:
*** Replied issues created by other teams in the class: https://github.com/CS2103JAN2018-F12-B4/main/issues/133[#133], https://github.com/CS2103JAN2018-F12-B4/main/issues/135[#135],
https://github.com/CS2103JAN2018-F12-B4/main/issues/138[#138], https://github.com/CS2103JAN2018-F12-B4/main/issues/139[#139], https://github.com/CS2103JAN2018-F12-B4/main/issues/141[#141]
*** Reported a bug for another team in the class: https://github.com/CS2103JAN2018-W14-B3/main/issues/96[#96]
** Tools:
*** Enabled branch protection for `master` and established guidelines for merging PRs and creating issues (with http://github.com[@melvintzw])
*** Integrated 4 new Github plugins to the team repo:
Travis CI (https://github.com/CS2103JAN2018-F12-B4/main/pulls/1[#1]),
AppVeyor (https://github.com/CS2103JAN2018-F12-B4/main/pulls/2[#2]),
Coveralls (https://github.com/CS2103JAN2018-F12-B4/main/pulls/149[#149]),
Netlify

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=commandsummary]

include::../UserGuide.adoc[tag=addcommand]

include::../UserGuide.adoc[tag=FAQ]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=tagcolours]

include::../DeveloperGuide.adoc[tag=keyboardshortcuts]
//@@author