= Kevin Yeong - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ContactSails

---

== Overview

ContactSails is a desktop application targeted for use for social media marketers based off AddressBook - Level 4 architecture.
It includes new features to allow the target group to perform their jobs more efficiently.
AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles.
The user interacts with it using a CLI, and it has a GUI created with JavaFX.
It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *features in improving compatibility with other applications such as data handling software by exporting relevant data in compatible file format*
** What it does: allows the user to export relevant data to a local file to aid workflow of the target group.
** Justification: This feature allows the user to export contact and order data to relevant file formats which can allow an integration of ContactSails into the users preferred workflow applications aiding their productivity and reduce resistance in accepting ContactSails usage in their workflow since the exported file is in a format which many productivity and data handling applications can view and edit.
** Highlights: This enhancement affects existing commands and commands to be added in future. Future possibilities include import features, UI for these features and possibly even having some functionality so users will have the option of data management within ContactSails instead and will not need to use the other applications. The implementation too was challenging for this release and thus was not implemented at this stage.

* *Code contributed*: [https://github.com/CS2103JAN2018-W13-B1/main/blob/master/collated/functional/A0143487X.md[Functional code]] [https://github.com/CS2103JAN2018-W13-B1/main/blob/master/collated/test/A0143487X.md[Test code]]

* *Other contributions*:

** Project management:
*** Contributed to releases on GitHub
** Community:
*** Reported bugs and suggestions for other teams in the class


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=exportdata]
