= Le Khang Tai - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Catalogue

---

== Overview

* This is a desktop Catalogue application. It has a GUI but most of the user interactions happen using a CLI (Command Line Interface).
* It is a Java application intended for librarians, students and guests using the library.

== Summary of contributions

* *Major enhancement*: added the ability to add and delete account Commands and the add/delete command parsers
** What it does: allows the user to add a new account into the existing account list and delete an account based on the username inside the account list.
** Justification: This feature improves the product significantly because a librarian can create borrowers (with privilege level of student) and create new administrators (with privilege level of librarian). The database of students will allow the students of National University of Singapore to borrow, return and reserve a book of their desire inside the library.
** Highlights:This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: NIL

* *Minor enhancement*:

* *Code contributed*:

* *Other contributions*:

** Project management:

** Enhancements to existing features:

** Documentation:

** Community:

** Tools:

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
