= Lim Jin Sheng Jason - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: contactHeRo

---

== Overview

contactHeRo is a desktop contact management application
made for Human Resource (HR) managers, specifically for
recruiters in a company.

== Summary of contributions

* *Major enhancement*: added the *login system* in contactHeRo.
** What it does: provides security for the user's data.
** Justification: Recruiters are dealing with data of their potential employees and some of these data are personal and sensitive. Recruiters may also have some confidential company data stored in the application. Hence it is necessary for them to set up some form of security to protect these sensitive data. Having a login system is one of the common methods to ensure data security.

** Highlights: This enhancement provides a foundation for other security measures to be implemented in contactHeRo in the future to futher help users in securing their important data.
** Credits: stackoverflow.com.

* *Minor enhancement*: added the *ability to clear history of user input*.
** What it does: It allows the user erase the past commands which was inputted in the command line.
** Justification: As our app only uses one command line interface for all user input and it comes with a history command which lets the user see the list previously entered commands,
this may expose some of the sensitive data which the user has inputted, like login username and password. Hence being able to clear away the history of user inputs can help to protect those sensitive information.
** Highlights: This was one of my first enhancement to the project and it helped me get familiarise with the logic component of the code.

* *Code contributed*: [https://github.com/CS2103JAN2018-W09-B2/main/blob/master/collated/functional/Jason1im.md[Functional code]]
[https://github.com/CS2103JAN2018-W09-B2/main/blob/master/collated/test/Jason1im.md[Test code]] +

* *Other contributions*:

** Project management:
*** Reach all the milestones `v1.1` - `v1.3rc` and `v1.5rc` on GitHub.
*** Created issues and milestones for the team.
** Enhancements to existing features:

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=login]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=login]



---
