= Meera Kanani - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Pigeons

---

== Overview

Pigeons is a desktop level application created for delivery companies to better assign and
organize deliveries for the delivery people.

== Summary of contributions

* *Major enhancement*: added *the ability to create an optimal delivery route when filtering the data
 by delivery date*
** What it does: allows the user to filter all the data by date of delivery and then creates an optimized route from the headquarters to all the delivery points for that day.
** Justification: This feature improves the product significantly because the user is meant to be someone who delivers packages and this make it easy for the user to determine where he has to go that day and what the best route is from his
starting location. This optimized route will be outputed as a map on the UI by another team member.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands but more importantly required creating new classes and methods that
could be referenced by other team members and would be usable for the UI.
** Credits: The Google API was used to get the distance between addresses, the java code was written around using this API.

* *Minor enhancement*: added a filter command that allows the user to filter the data by date (delivery date).

* *Minor enhancement*: added a getTime function that gets the time of the entire journey for the delivery man and can be displayed on the UI.

//TODO add links for collation
* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Kept team on track on TODO's before each tutorial
** Enhancements to existing features:
*** Wrote additional tests for existing features to increase coverage
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
*** Modified existing guides to include the premises of our project
*** Removed items of the user guide, developer guide etc that were relevant for our project]
*** Added documentation for all the features I added in the dev guide and user guide.
*** Modifed the README doc
** Community:
*** PRs reviewed (with non-trivial review comments)

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=filter]

include::../UserGuide.adoc[tag=testing]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=filter]

include::../DeveloperGuide.adoc[tag=optimize]

include::../DeveloperGuide.adoc[tag=sort]


