= John Doe - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 4

---

== Overview

CoinBook is a desktop Cryptocurrency management app for storing and keeping track of one’s
cryptocurrency portfolio. The user interacts with it using a CLI, and it has a GUI created with JavaFX.
It is a Java application targeted at enthusiasts or investors who trade heavily and actively in
cryptocurrencies. It provides users a single platform on which they can check news and statistics along
with managing their cryptocurrency portfolio.

== Summary of contributions

* *Major enhancement*: added the *ability to sort Coin List*
** What it does: allows the user to sort list of coins by alphabetical order.
** Justification: This feature improves the product significantly because a user can make arrange his coins in such a way that is easier for him to view and find the desired coin he wants to interact with, especially if said user has a diverse and big portfolio to deal with.
** Highlights: This enhancement does not affect any existing commands and is a standalone feature. It did not require in-depth analysis however the implementation was relatively challenging as some understanding of the inter-link between the ParserUtil, CoinBookParser, ModelManager and Model classes was essential in figuring out how to eventually make the SortCommand function come to fruition.
** Credits: _Required some help to search other implementations of other sort functions in order to understand how to apply it for our own CoinBook_
* *Minor enhancement*: added an additional option that allows for sorting by reverse alphabetical order by adding another case.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo] //haven't added in my tag yet

include::../UserGuide.adoc[tag=dataencryption] //haven't added in my tag yet

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=organisation]

include::../DeveloperGuide.adoc[tag=dataencryption]
