= Pearlissa Taim Qi Yah - Project Portfolio

:repoURL: https://github.com/CS2103JAN2018-F09-B1/main

== Project: Your TA

'''

== Overview

Your TA is a desktop contact, calendar and task manager application that caters to tech-savvy university Teaching Assistants and/or Professors/Lecturers. +
It allows the user to manage their deadlines, as well as keep track of their students. +
The user is mostly required to interact with the application through a Command Line Interface (CLI), along with minimal Graphical User Interface (GUI) features created with JavaFX. It is written in Java, and has about 15 kLoC.

== Summary of Contributions

* *Major feature*: Implemented a *login* system

** What it does: Requires users to log in to their accounts (and create accounts for first-time users) with a username and password to access their personal data

** Justification: This feature makes *Your TA* much more accessible to multiple users as it ensures that each user only has access to their own personal information, and not those of other users.

** Highlights: This feature precedes all other functionalities when starting up the application. It is also the first attempt at increasing data security of the software. It required an in-depth analysis of how the `Model` and `Storage` components work. The implementation too was challenging as it called for a lot of new models, managers and UI to be created from scratch.

** Credits: Adapted classes from `Model` and `Storage` components.

* *Minor feature*: Added *sort* that allows user to sort contacts alphanumerically based on name

* *Minor feature*: Created a new *theme* for the software

* *Code contributed*: link:{repoURL}/collated/functional/JoonKai1995.md[functional], link:{repoURL}/collated/test/JoonKai1995.md[test].

* *Other contributions*: _TO BE FILLED IN_

<<<

== Contributions to the User Guide

*****
_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
*****

=== Sorting all entries : `sort`

Sorts all entries from the address book in alphabetical order based on name. +
Alias: `s` +
Format: `sort`

== Login Feature

Before you are able to access the application, login is required.
====
* Enter your `Username` and `Password` in the respective fields. +
* Click on the `login` button.
* If you have entered either of those incorrectly, the text "Wrong username or password entered" will be displayed. You have an unlimited number of tries to log in. +
* Upon successful login, the application will load with your previously saved data.
====

[NOTE]
Both `Username` and `Password` fields are case-sensitive.

[TIP]
If you are a first-time user, create an account by entering your desired `Username` and `Password` in the username and password text fields respectively. +
Then, click on the `Login` button.

== Contributions to the Developer guide

*****
_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
*****

== Design

=== Model

...

The `Task` Class:

* Stores the information of a specific task in the AddressBook
* Information includes: Task Description, Deadline, Priority.
* Implements `UniqueTaskList` that enforces uniqueness of its elements and disallows nulls.
* `Task Description`: Object that stores the task description of the `Task` Object.
[NOTE]
Task's name can contain any alphanumeric characters, but should not be null.
* `Deadline`: Object that stores the deadline of the `Task` Object.
[NOTE]
Deadline should not be dates of the past and should only be in the format dd-mm-yyyy.
* `Priority`: Object that stores the priority of the `Task` Object.
[NOTE]
Priority should only be a value from 1 to 3, 1 being the lowest and 3 being the highest.

The `Task` Class:

* Stores the information of a specific Task in Your TA.
* Information includes: Title, Description, Deadline, Priority.
* Implements `UniqueTaskList` that enforces uniqueness of its elements and disallows nulls.
* `Title` & `TaskDescription`: Object that stores the title and description of the `Task` Object.
[NOTE]
Tasks title and description should only contain alphanumeric characters, and should not be null.
* `Deadline`: Object that stores the deadline of the `Task` Object.
[NOTE]
Deadline should be a valid date that exists and in the format dd-mm-yyyy. Tasks cannot be scheduled in the past. And can only be scheduled at most 6 months in advance. (Based on months: tasks cannot be scheduled on 1st August 2018 if the current date is 31st January 2018).
* `Priority`: Object that stores the priority of the `Task` Object.
[NOTE]
Priority value input can only be a value from 1 to 3. 1 being lowest priority and 3 being highest.

== Implementation

...

=== Toggling Between Themes: Light and Dark (Since v1.5)

This feature allows the user to toggle between 2 preset themes, light and dark.

==== Current implementation

The user will click on the drop-down menu tab labeled `Switch Theme`, and select the `toggle` button to toggle to the other theme that is not currently in use.

==== Design Considerations

===== Aspect: How much freedom is given to the user in terms of customisation

* **Alternative 1 (current choice):** Use 2 preset css files, `LightTheme.css` and `DarkTheme.css`, restrict toggling between these 2 presets only. Change the controller class `MainWindow.java` between 2 fxml files, `DarkMainWindow.fxml` and `LightMainWindow.fxml`.
** Pros: Simple to implement and user friendly. User can switch to a different theme with a click of a button.
** Cons: User cannot customize the themes at all, only have 2 choices, light or dark.
* **Alternative 2:** Allow user to customise and pick a colour for each aspect. e.g. background colour, text colour etc.
** Pros: User have full ability to customise the colours of different aspects the app.
** Cons: Heavy on programming (need to add a lot more cases into the css file(s)). User can create hideous themes.

==== Future enhancements (Coming in v2.0)

Add more themes that can be chosen from the theme drop-down box so that the user has more choices.

=== Tasks on Calendar View (Since v1.5)

This feature allows the user to see the calendar on the UI and see the scheduled `Task` deadlines on the calendar.

==== Current implementation

The user will enter a command `addTask title/TITLE desc/DESCRIPTION by/DEADLINE priority/PRIORITY` to the application. The application will then rely on `AddressBookparser` and
parse the argument. The argument will be passed into the AddTaskCommand to be executed. From there, it will create a new `Task` object that will be
added to the `calendarList` of the `UniqueTaskList` which in turn will be displayed on the date of the deadline, on the calendar.

==== Design Considerations

===== Aspect: How to link specific tasks to the correct calendar nodes

* **Alternative 1 (current choice):** Use a 7 by 32, 2D `Array` to store the tasks to be added into the calendar.
** Pros: Separate from the Task list (less prone to bugs). Faster run time (does not need to iterate through all tasks).
** Cons: Higher memory usage constraint, can only schedule tasks up to 6 months in advance to prevent high memory usage that will affect the speed and performance of the app.
* **Alternative 2:** Use the task list itself to be displayed in the calendar.
** Pros: Easier to program and less memory usage (only 1 task list is used without another 2D array for the calendar), tasks can be scheduled as far ahead as desired.
** Cons: Needs to iterate through the entire task list for every calendar node when loading the calendar view (slows performance when dealing with tasks).

==== Future enhancements (Coming in v2.0)

Link specific key-press or select actions to the todo list such that a click on either side will display the selected task on the other.