= Samuel Loh- Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Codeducator

---

== Overview

Codeducator is a desktop address book application for private programming language tutors.
Users are able to track the progress of their students, manage their tutoring schedule and other important information about their students. +

Codeducator has a graphical user interface built with JavaFX but most of the user interactions are done using command line interface. It is written in Java and has about 10 kLoC. +

This project is based on the https://github.com/se-edu/addressbook-level4[AddressBook-Level4] created by the SE-EDU initiative.

== Summary of contributions

* *Major enhancement*: added *a separate profile page for students and the ability to edit their miscellaneous details.*

** What it does:
*** The profile page allows the tutor to view a student's full information paticulars on a separate page.
*** This profile page includes the main information of a student (also displayed on the student card), miscellaneous information and profile picture (both not displayed on the student card)
*** The tutor will be able to edit all of the student's information displayed on the profile page. This includes the profile picture which is done by proving a filepath to the new picture.

** Justification: A tutor would wish to learn as much details as he/she can of a student before taking one in. In the Codeducator app, there is a panel of cards to display each student's information.
However, it is relatively small. Moreover, some details like Next-Of-Kin contact is important, yet not required very often. Thus this enhancement aids the tutor in viewing and keeping track of the full details of each student.

** Highlights: This feature was implemented partially using HTML and JavaScript and hence further changes to it will have to consider both the source code and the HTML/JavaScript files.

* *Minor enhancement*: Added *a 'ProgrammingLanguage' field to the student model.*

** What it does: Allows the tutor to keep track of what programming language(s) are being used or taught to each student.

**Justification: A tutor would want to keep track of what programming language a student is learning with or about, in order to better prepare lessons for that student.

* *Code contributed*: [https://github.com/CS2103JAN2018-W09-B3/main/blob/master/collated/functional/samuelloh.md[Functional code]] [https://github.com/CS2103JAN2018-W09-B3/main/blob/master/collated/test/samuelloh.md[Test code]]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Setup Github organisation and repositories for the team.
*** Managed release `v1.5rc` (1 release) on GitHub.

** Enhancements to existing features:
*** Added Programming Language field to student model.

** Documentation:
*** Corrected and improved on some language and grammar errors.

** Community:
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/CS2103JAN2018-W11-B3/main/issues/125[1], https://github.com/CS2103JAN2018-W11-B3/main/issues/123[2], https://github.com/CS2103JAN2018-W11-B3/main/issues/113m[3], https://github.com/CS2103JAN2018-W11-B3/main/issues/105[4], https://github.com/CS2103JAN2018-W11-B3/main/issues/105[5])


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

Start of extract from [User Guide]

include::../UserGuide.adoc[tag=profilePage1]
include::../UserGuide.adoc[tag=profilePage2]

End of extract from [User Guide]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

Start of extract from [Developer Guide]

include::../DeveloperGuide.adoc[tag=programmingLanguage]
include::../DeveloperGuide.adoc[tag=profilePage1]
include::../DeveloperGuide.adoc[tag=profilePage2]

End of extract from [Developer Guide]
