= Eric Zhou - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: TravelBanker

---

== Overview

This application allows travelers to keep track of money borrowed or lent from other people. It is a command line based application that consists of a JavaFX GUI. The application GUI consists of the addressbook with relevant info, a CLI, a status box etc.
== Summary of Contributions

* *Major Enhancement*: Implemented currency conversion feature to allow people to quickly convert their currencies from one currency to another. Total balances can also be converted.
** What it does: The command allows users to convert specific entries' balances from one currency to another currency. This allows the user to convert to different currencies because it is not clear where the user will be located. The feature supports 170 currencies.
** Justification: It is not guaranteeed that a certain person will be in the same location or use the same currency as the owner so it is neccesary to have a currency converter that can allow people to use the application from all around the world.
** Credits:
Used third-party currency converter library from github: https://github.com/Ritaja/java-exchange-rates

* *Minor Enhancement*: Allow users to wipe all balances in their addressbook, show the all the people who owe the user money, and all the people who the user owes money to, added support for negative balances for money field


* *Code contributed*: [https://github.com/CS2103JAN2018-T11-B4/main/blob/master/collated/functional/software-1234.md[Functional code]] [https://github.com/CS2103JAN2018-T11-B4/main/blob/master/collated/test/software-1234.md[Test code]]


* *Other contributions*:

** Project management:
*** Contributed code from v1.0 on
*** Created milestones from v1.2 to v1.5rc and managed release for v1.3.
*** Created issues and ensured they were relevant to the epics from v1.2 on

** Documentation:
*** Updated documentation to ensure latest versions were correct
** Tools:
*** Added new third party library (https://github.com/Ritaja/java-exchange-rates) to use for currency conversion

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=convert]
include::../UserGuide.adoc[tag=wipe]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=posneg]
include::../DeveloperGuide.adoc[tag=convert]









