= Tan Quan Rong Kaiser - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Session Logger and Planner (SLAP) for Social Workers

---

== Overview

Session Logger and Planner (SLAP) for Social Workers is for those who prefer to use a desktop app for managing their schedule and contacts*. More importantly, SLAP is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI). If you can type fast, SLAP can get your daily scheduling and contact management tasks done faster than traditional GUI apps.
It is a simple Java application intended for social workers to help them plan their day and keep track of their beneficiaries. Some key features of this application include secure sign-in, an address book, a calendar, a daily schedule display, user session logs and maps. Written in Java, it has about 15 kLoC.

SLAP aims to target social workers who have to visit different less privileged families and/or high-risk
stay-at-home patients as their daily routine. SLAP allow them to organise their schedule for the day as
they may have to visit multiple locations, take copious notes and help in many different ways.

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

=== Features

include::../UserGuide.adoc[tag=authentication]

include::../UserGuide.adoc[tag=sessionlog]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

=== Design and Implementation

include::../DeveloperGuide.adoc[tag=multiuser]

include::../DeveloperGuide.adoc[tag=authentication]

include::../DeveloperGuide.adoc[tag=dataencryption]

=== Use Cases

include::../DeveloperGuide.adoc[tag=kaiserUseCases]

=== Instructions for Manual Tests

include::../DeveloperGuide.adoc[tag=kaiserManualTests]
