= Wang Jinyi - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CelebManager

---

== Overview

CelebManager is a software application that allows celebrity managers to maintain schedules of celebrities under them.
It is optimized for users who prefer to work with a Command Line Interface (CLI) while still having a
Graphical User Interface (GUI) for visual feedback.

In this software, the users will be able to:

.   Manage contacts
.	Manage appointments
.	Manage calendars
.	Plan efficient routes

This project portfolio summarises my contribution towards the development of CelebManager.

== Summary of contributions

* *Major enhancement*: added *support for interacting with the calendar using CLI*
** What it does: This enhancement includes commands: `viewCalendar`, `viewCombinedCalendar`, `viewCalendarBy`, and
`viewDate`. With these commands, users can view different celebrities' calendars, a joint calendar of all celebrities,
a day's or week's or month's appointments, and change base date of the calendar.
** Justification: This feature improves the product significantly because it allows users to interact with the
calendar inside CeleManager and makes the calendar a powerful visualisation tool to view timings of appointments.
** Highlights: The implementation requires comprehension of CalendarFX's API and experimenting with the API to
understand which methods to be used to update the calendar UI. Also, additional variables were created
to keep track of the current calendar's status to preserve the original ways of interaction between different
components.
** Credits: [http://dlsc.com/wp-content/html/calendarfx/apidocs/index.html[CalendarFX]]

* *Major enhancement*: added *the ability to delete an appointment*
** What it does: This enhancement refers to the command, `deleteAppointment`. It allows users to delete an existing
appointment.
** Justification: This feature improves the product significantly because users can delete a specified appointment to
get rid of appointments that are cancelled or no longer needed.
** Highlights: This enhancement requires an understanding of how appointments are stored and can be removed from the
calendar visually.
** Credits: [http://dlsc.com/wp-content/html/calendarfx/apidocs/index.html[CalendarFX]]

* *Minor enhancement*: added *the ability to list appointments within a given date range*

* *Minor enhancement*: added *the ability to remove a tag from all contacts*

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Enhancements to existing features:
*** Added support for deleting celebrity using the existing command `delete`. This enhancement ensures the removal
of the deleted celebrity from the appointments he/she is attending, as well as the deletion of his/her calendar.
(Pull request:)
*** Created TypicalCelebrities, modified getTypicalPersons to facilitate testing of new features (Pull request:)
** Documentation:
*** Standardised the language of existing contents of the User Guide: https://github.com[#14]
*** Collated codes for `v1.4` release
** Community:
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide.
They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=view-calendar] +
include::../UserGuide.adoc[tag=deleteAppointment] +
include::../UserGuide.adoc[tag=removeTag]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide.
They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=removeTag] +
include::../DeveloperGuide.adoc[tag=deleteAppointment]
