= Zhang Zequn - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Delivery

---

== Overview

Delivery is a desktop application designed for restaurants who want to maintain their own system to keep track customers’ orders. It is optimized for those who prefer to work with a Command Line Interface (CLI) while still having the benefits of a Graphical User Interface (GUI). It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the order feature* for AddCommand and *checked whether the order is available*
** What it does: allows the user to key in the order made by customers, and check whether the ordered dish is available in the restaurants' menu.
** Justification: This feature enables the main functionality of the Delivery app, because the app is serving the purpose to keep track customers' orders. By checking whether the ordered food is available in the menu, the user can decide whether customers can order the particular dish.
** Highlights: Adding the order feature requires updates for AddCommand and EditCommand as well as all the relevant methods and data structure involved. Enabling the checking process needs to main a local menu storage for all the dishes available. Maintaining the dishes inside the menu by commands will be available in upcoming version 2.0.

* *Minor enhancement*: Add colours to different tags.
** Justification: Same tags will be assigned the same colours which makes the differentiation of tags clearer.

* *Minor enhancement*: Add Optional Halal/Non-halal and Vegetarian/Non-vegetarian features.
** What it does: allows the user to key in the optional Halal/Non-halal and Vegetarian/Non-vegetarian features. If the user did not key in values for these two features, the default value is Non-halal and Non-vegetarian.
** Justification: This allows the restaurants to have a clear view about whether the customer is halal and vegetarian, hence can better prepare for the food.

* *Code contributed*: [https://github.com/CS2103JAN2018-F11-B4/main/blob/master/collated/functional/ZacZequn.md[Functional code]] [https://github.com/CS2103JAN2018-F11-B4/main/blob/master/collated/test/ZacZequn.md[Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` (1 releases) on GitHub
** Enhancements to existing features:
*** Add colours to different tags (Pull requests https://github.com/CS2103JAN2018-F11-B4/main/commit/69a6fb5ceccc27452f8f3c698aa2671fb9a61c02[#4])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Update relevant parts for User Guide and Developer Guide
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://nus-cs2103-ay1718s2.slack.com/archives/D9M8Y20Q2/p1520616066000038[1])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/CS2103JAN2018-T16-B1/main/issues/87[1], https://github.com/CS2103JAN2018-T16-B1/main/issues/80[2], https://github.com/CS2103JAN2018-T16-B1/main/issues/73[3])_{These issues were created by me, but it shows that my team mate created them on gitHub. I think this could because that I was re-assigned to this group during the mock PE.}_

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]



