= Zhang Yijiong - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Delivery

---

== Overview

Delivery is targeted at restaurants, especially for the small-medium ones, which want to have a system to keep track customers’ orders and delivery.

A restaurant can have hundreds of orders a day and it’s extremely troublesome for the restaurant stuff to manually write down all customer information (including their names, contact numbers, addresses, orders and expected time of delivery etc.) and keep track on it.

Hence, they need a software to store all the information mentioned above in an organised manner.

Delivery is for those who *prefer to use a desktop app for managing orders*. More importantly, Delivery is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI). If you can type fast, Delivery can manage the orders faster than traditional GUI apps. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *an separate order processing queue to process order* including processOrder,
processNextOrder, processMoreOrder, completeOneOrder, completeMoreOrder and tag commands.
** What it does: User is able to input orders from order book into the processing queue, indicating that the order is
being processed(cooking).
** What can it do in the future: When an order is completed from the queue, the total price of the order could automatically
be added into the daily revenue, for additional accounting purposes.
** Justification: This feature improves the product significantly, as firstly it separates the recording and processing of orders.
When an order has been cooked, it is removed from the processing queue, but still remains in order book, in case
there is any future usage for reference. Secondly, the owner can have a clearer idea about what is the status of
his kitchens are doing, so that he can manage them more efficiently.
** Highlights: This enhancement does not affect commands such as "add", "delete" or others on the order book.

* *Minor enhancement*: added an path feature.
** What is does: Show the path from user(restaurants owners)'s address to the customer's address. As a result,
user can roughly estimate how long does it take to deliver the food.
** Justification: The ability to estimate the delivery timing is crucial as the user would be able to determine whether to take the order.

* *Minor enhancement*: added an inner ordering for person(Order) object in UniquePersonList(Order book).
** What is does: When an order is labelled with different tag, its position in the order book would change.
For instance, the order labelled 'Cooked' would jump to the front of the list to remind restaurant owner to quickly
send out delivery man. Another example would be that orders labelled with 'Delivered' would sink to the
bottom of the list so that the owner would not to worry about them.
** Justification: If there is no such implementation, the new orders would always be below the older orders and
it might be very troublesome to scroll down to see them, especially when the number of orders gets bigger.
Besides, the different priority for order in different status can improve restaurants' efficiency.

* *Code contributed*: [https://github.com/CS2103JAN2018-F11-B4/main/blob/master/collated/functional/ZhangYijiong.md[Functional code]] [https://github.com/CS2103JAN2018-F11-B4/main/blob/master/collated/test/ZhangYijiong.md[Test code]]

* *Other contributions*:

** Enhancements to existing features:
*** Modify select command to show the address of the order on Google Map (Pull requests https://github.com/CS2103JAN2018-F11-B4/main/commit/eed0e01164840261c1dff085b4205956e77913a8[#30])
** Small Enhancement
*** Added a load web page function which loads web page in the browser panel.
** Documentation:
*** Updated contents of the User Guide and the Developer Guide frequently.
** Community:
*** Reported bugs and suggestions for other teams in the class (examples: https://github.com/CS2103JAN2018-F09-B2/main/issues/130[1] https://github.com/CS2103JAN2018-F09-B2/main/issues/128[2] https://github.com/CS2103JAN2018-F09-B2/main/issues/123[3] )
** Tools:
*** Deployed Travis to own repo

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users.
|===

include::../UserGuide.adoc[tag=ProcessingQueue]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=ProcessingQueue]
include::../DeveloperGuide.adoc[tag=Path]

