= Jasmund Toh - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CLIndar

---

== Overview

CLIndar is a desktop application written mainly in Java that helps university computing students
to manage their tasks and events. The user interacts with it using a CLI. It has a GUI made using
JavaFX.

== Summary of contributions

* *Major enhancement*: Changing of the GUI and 'Listing' feature
** What is done: Configuration of the UI with the backend components to feature the task and events panel, and CalenderFX.
Also allows users to configure to GUI to their personal preference.
** Justification: This feature helps users of CLIndar to keep view their tasks and events to their personal needs and
have access to their calendar simultaneously.
** Highlights: Competent knowledge about JavaFX coupled with design concepts are required to make a drastic yet appealing
change to the UI. Integration is also required for CalendarFX with the rest of the system.
** Credits: Referring to code.makery http://code.makery.ch/library/javafx-8-tutorial/part3/ helped out a lot in enabling
me to pick up JavaFX in short period of time

* *Minor enhancement #1*: Added 'help' command
** What it does: Displays help with respect to the command request by the user.
** Highlights: This feature is a modification to the add and delete commands. It takes into account the new model of
CLIndar.
** Justification: This makes CLIndar more 'LINUX' like which is our original intent to fit our project scope.