= Ryan Ang - Project Portfolio
:imagesDir: images
:stylesDir: stylesheets

== PROJECT: ReciRecipé

Welcome to my portfolio page for CS2103T Academic Year 2018 Semester 2 project - ReciRecipé.

== Project Overview

include::./UserGuide.adoc[tag=applicationDescription]

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

[[code-contributions]]
== Summary of contributions

=== Enhancement: Unique Tag Colors
==== Why?
Users love visually aesthetic applications! But on a more serious note, different tag colors help users differentiate their tags at at glance.

This feature has been implemented in version 1.1, in PR link:https://github.com/CS2103JAN2018-F09-B2/main/pull/5[#5].

include::./DeveloperGuide.adoc[tag=unique-tag-colors]

=== Enhancement: Embedded URL
==== Why?
A user may want to save an online recipe, or perhaps even a YouTube video, into ReciRecipé.

This feature has been implemented in version 1.1, in PR link:https://github.com/CS2103JAN2018-F09-B2/main/pull/35[#35].

include::./DeveloperGuide.adoc[tag=embedded-url]

=== New feature: Facebook Compatibility
==== Why?
In this modern day and age, users like to share their lives with their friends. Why not share recipes too?

This feature has been implemented in version 1.3, in PR link:https://github.com/CS2103JAN2018-F09-B2/main/pull/74[#74].

include::./UserGuide.adoc[leveloffset=1,tag=share-command]

include::./DeveloperGuide.adoc[tag=facebook-compatibility]

=== New feature: Image Support
==== Why?
Users want to know how awesome their dish looks like once they have cooked it.

This feature has been implemented in version 1.4, in PR link:https://github.com/CS2103JAN2018-F09-B2/main/pull/86[#86].

include::./DeveloperGuide.adoc[tag=inserting-an-image]

== Other contributions

Listed below are other contributions I have made to the ReciRecipé project:

* UI Design:
** Redesigned the layout and appearance of the original UI.

* Project Management:
** Set up team organisation and repository.
** Managed issues on GitHub.
** Reviewed teammates' pull requests via GitHub.

* Other Documentation Contributions:
** Contributed to User Stories and Use Cases.

